RateMyServices/urls.py
from django.urls import path, include
from . import views

from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

app_name = 'RateMyServices'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:generaluser_id>/search', views.search, name='search'),
	path('<int:generaluser_id>/search/filter', views.filter, name='filter'),
	path('<int:professionaluser_id>&<int:generaluser_id>/', views.user_profile, name='user_profile'),
	path('rate/', views.rate, name='rate'),
	# userprofile
	path('login', auth_views.LoginView.as_view(), name='login'),
	path('logout', auth_views.LogoutView.as_view(), name='logout'),
	path('signup', views.signup_view , name='signup_view'),
	path('MyProfile', views.my_profile, name='my_profile'),
	path('general_profile/<int:generaluser_id>/', views.general_profile, name='general_profile'),
	path('professional_profile/<int:professionaluser_id>/', views.professional_profile, name='professional_profile'),
	path('professional_profile/<int:professionaluser_id>/<int:service_id>', views.professional_profile, name='professional_profile_service'),
	path('upgrade_plans', views.upgrade_plans, name='becomePremium'),
	path('becomeProUser/<int:generaluser_id>/', views.becomeProUser, name='becomeProUser'),
	path('addProUser/<int:generaluser_id>/', views.addProUser, name="addProUser"),
	path('addService/<int:generaluser_id>/', views.addService, name='addService'),
	path('addServicePage/<int:generaluser_id>/', views.addServicePage, name='addServicePage'),
	path('hire/', views.hire_service, name='hire'),
	path('deleteService/', views.delete_service, name='deleteService'),

	# URL FOR EDIT USER
	path('professional_profile/<int:professionaluser_id>/edit_profile/',views.editUser_view, name='editProfile'),
	path('editInfo/', views.update_user_info, name='updateUserInfo'),
]

services/urls.py
from django.contrib import admin
from django.urls import include, path
from RateMyServices import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('RateMyServices/', include('RateMyServices.urls', 'django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RateMyServices/models.py
from django.db import models
from accounts.models import User
from django.db import models

# Create your models here.

# class GeneralUser(models.Model):
# 	first_name = models.CharField(max_length=30)
# 	last_name = models.CharField(max_length=30)
# 	email = models.EmailField()
# 	password = models.CharField(max_length=30)
# 	state = models.CharField(max_length=30)
# 	city = models.CharField(max_length=30)
# 	zips = models.CharField(max_length=5)
# 	street = models.CharField(max_length=100)
# 	phone = models.CharField(max_length=12)
	
# 	def __str__(self):
# 		return self.first_name + " " + self.last_name + ", " + self.email

# 	def get_full_name(self):
# 		full_name = self.first_name + " " + self.last_name
# 		return self.full_name

class ProfessionalUser(models.Model):
	generalUserID = models.ForeignKey(User, on_delete=models.CASCADE)
	title = models.CharField(max_length=30, default='')
	description = models.CharField(max_length=200, default='')
	avg_rating = models.FloatField(default=0.0)
	isPlatinum = models.BooleanField(default=False)
	isDiamond = models.BooleanField(default=False)
	def __str__(self):
		return self.generalUserID.first_name + " " + self.generalUserID.last_name + " (" + self.generalUserID.email + ")"

class Service(models.Model):
	service = models.CharField(max_length=30)
	provider = models.ForeignKey(ProfessionalUser, on_delete=models.CASCADE)
	rate = models.FloatField()
	avg_rating = models.FloatField(default=0.0)
	description = models.CharField(max_length=200, default='')
	isHour = models.BooleanField(default=False)
	image = models.ImageField(upload_to='service_pics/',blank=True)
	hireCount = models.PositiveIntegerField(default=0)
	def __str__(self):
		return self.service + ": " + self.provider.generalUserID.first_name + " " + self.provider.generalUserID.last_name + ", " + str(self.rate)
	
	def updateName(self, newServiceName):
		self.service = newServiceName
		self.save()
	def updateDescription(self, newDescription):
		self.description = newDescription
		self.save()
	def updatePrice(self, newPrice):
		self.rate = newPrice
		self.save()
	def updateIsHour(self, newIsHour):
		self.isHour = newIsHour
		self.save()
	def addOneHireCount(self):
		self.hireCount += 1
		self.save()

class Rating(models.Model):
	rater = models.ForeignKey(User, on_delete=models.CASCADE)
	provider = models.ForeignKey(ProfessionalUser, on_delete=models.CASCADE)
	service = models.ForeignKey(Service, on_delete=models.CASCADE, default=None)
	rating = models.IntegerField()
	description = models.CharField(max_length=200)
	verified = models.BooleanField(default=False)
	def __str__(self):
		return self.rater.first_name + ", " + self.provider.generalUserID.first_name + ", " + str(self.rating)

class Transaction(models.Model):
	buyer = models.ForeignKey(User, on_delete=models.CASCADE)
	provider = models.ForeignKey(ProfessionalUser, on_delete=models.CASCADE)
	service = models.ForeignKey(Service, on_delete=models.CASCADE)
	def __str__(self):
		return self.buyer.first_name + ", " + self.provider.generalUserID.first_name + ", " + self.service.service

class Advertisment(models.Model):
	provider = models.ForeignKey(ProfessionalUser, on_delete=models.CASCADE)
	ad = models.ImageField(upload_to='static/images/ads')

class UserImages(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='static/images/users')

# PostPicutre
class Post(models.Model):
    title = models.TextField()
    cover = models.ImageField(upload_to='images/')

RateMyServices/views.py
from django.shortcuts import *
from django.http import *
from .models import *
from django.template import *
from django.urls import *
from django.views import *
from django.core import *

# for signup
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.views import generic
from accounts.forms import RegisterForm
from accounts.models import User

#for Image Upload
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage

#Edit User Details
from accounts.forms import UserChangeForm


# Create your views here.
def user_profile(request, professionaluser_id, generaluser_id):
	pUser = get_object_or_404(ProfessionalUser, id=professionaluser_id)
	gUser = get_object_or_404(User, id=generaluser_id)
	return render(request, 'RateMyServices/user_profile.html', {'pUser': pUser, 'gUser': gUser})

def rate(request):
	pUser = get_object_or_404(ProfessionalUser, id=request.POST['provider'])
	gUser = get_object_or_404(User, id=request.user.id)
	service = get_object_or_404(Service, id=request.POST['service'])

	if Transaction.objects.filter(buyer=gUser, provider=pUser, service=service).count() == 0:
		verified = False

	else:
		verified = True

	pUser.rating_set.create(rater=gUser, provider=pUser, service=service, rating=int(request.POST['rating']), description=request.POST['description'], verified=verified)

	if pUser.avg_rating == 0:
		pUser.avg_rating = float(request.POST['rating'])
		pUser.save()

	else:
		new_rating = (pUser.avg_rating + float(request.POST['rating']))/2.0
		pUser.avg_rating = new_rating
		pUser.save()

	if service.avg_rating == 0:
		service.avg_rating = float(request.POST['rating'])
		service.save()
	
	else:
		new_rating = (service.avg_rating + float(request.POST['rating']))/2.0
		service.avg_rating = new_rating
		service.save()

	return HttpResponseRedirect(reverse('RateMyServices:professional_profile', args=(pUser.id,)))

def index(request): 
	gUser = User.objects.get(id=1) #id = 2 : for testing purposes
	pUsers = ProfessionalUser.objects.all()
	serviceList = Service.objects.order_by('-hireCount')[:10]
	platinumList = Service.objects.filter(provider__isPlatinum=True).order_by('-hireCount')[:10]
	diamondList = Service.objects.filter(provider__isDiamond=True).order_by('-hireCount')[:10]

	context = {
		'pUsers': pUsers,
		'gUser': gUser,
		'serviceList': serviceList,
		'platinumList': platinumList,
		'diamondList': diamondList,
	}
	return render(request, 'RateMyServices/index.html', context)

def search(request, generaluser_id):
	gUser = get_object_or_404(User, id=generaluser_id)
	services = Service.objects.all()

	if len(request.POST['search']) == 0:
		if len(request.POST['state']) != 0:
			filtered_services = list()
			for service in services:
				if service.provider.generalUserID.state == request.POST['state']:
					if len(request.POST['city']) != 0:
						if service.provider.generalUserID.city == request.POST['city']:
							filtered_services.append(service)

					else:
						filtered_services.append(service)

			services = filtered_services

	

	else:
		services = services.filter(service__icontains=request.POST['search'])

		if len(request.POST['state']) != 0:
			filtered_services = list()
			for service in services:
				if service.provider.generalUserID.state == request.POST['state']:
					if len(request.POST['city']) != 0:
						if service.provider.generalUserID.city == request.POST['city']:
							filtered_services.append(service)

					else:
						filtered_services.append(service)

			services = filtered_services

	json_services = serializers.serialize('json', services)

	request.session['services'] = json_services

	context = {
		'services': services,
		'gUser': gUser
	}
	return render(request, 'RateMyServices/results.html', context)

def filter(request, generaluser_id):
	gUser = get_object_or_404(User, id=generaluser_id)
	serialize_list = request.session.get('services', None)
	deserialize_list = serializers.deserialize("json", serialize_list )
	services = [item.object for item in deserialize_list]
	filtered_services = list()

	if 'rating' in request.POST:
		rating_value = int(request.POST['rating'])
		for service in services:
			if service.avg_rating >= rating_value:
				filtered_services.append(service)

	elif 'rate' in request.POST:
		rate_value = int(request.POST['rate'])
		for service in services:
			if service.rate <= rate_value:
				filtered_services.append(service)

	services = filtered_services

	context = {
		'services': services,
		'gUser': gUser
	}
	return render(request, 'RateMyServices/results.html', context)

 
# Unused for now
'''
def login(request):
	return render(request, 'registration/login.html')
'''

def my_profile(request, service_id=None):
	def uploadProfileImage(userObj):
		if request.method == 'POST' and request.FILES.get('profile_image',False):
			# check if users did select files
			uploaded_file = request.FILES['profile_image']
			userObj.profile_image.delete()
			userObj.profile_image = uploaded_file
			userObj.save()
	def uploadServiceImage():
		if request.method == 'POST' and request.FILES.get('service_image',False):
			uploaded_file = request.FILES['service_image']
			serviceObj = get_object_or_404(Service, id=request.POST['service_id'])
			serviceObj.image.delete()
			serviceObj.image = uploaded_file
			serviceObj.save()
	def deleteServiceImage():
		if request.method == 'POST' and request.POST.get('delete_photo',False):
			serviceObj = get_object_or_404(Service, id=request.POST['service_id'])
			serviceObj.image.delete()
			serviceObj.save()
	def updateServiceInfo():
		isUpdateServiceInfo = False
		checkList = ['service','description','rate','isHour']
		for i in checkList:
			if request.POST.get(i,False):
				isUpdateServiceInfo= True
		if request.method == 'POST' and isUpdateServiceInfo:
			service = get_object_or_404(Service, id=request.POST['service_id'])
			if request.POST['service']:
				service.updateName(request.POST['service'])
			if request.POST['description']:
				service.updateDescription(request.POST['description'])
			if request.POST['rate']:
				service.updatePrice(request.POST['rate'])
			if request.POST.get('isHour',False):
				service.updateIsHour(True)
			else:
				service.updateIsHour(False)
	
	if request.method == 'POST' and request.POST.get('service_id',False):
		service_id = int(request.POST['service_id'])
	editable = True
	if request.user.is_authenticated:
		if request.user.is_professional:
			puser_id = request.user.professionaluser_set.all()[0].id
			uploadProfileImage(request.user)
			uploadServiceImage()
			deleteServiceImage()
			updateServiceInfo()
			return professional_profile(request, puser_id,service_id=service_id, editable=editable)
		else:
			guser_id = request.user.id
			uploadProfileImage(request.user)
			return general_profile(request, guser_id, editable)
	else:
		message = 'The action you try to do requires log in, please log in and precede.'
		context = {
			'message': message,
		}
		return HttpResponseRedirect(reverse('RateMyServices:login'))

def general_profile(request, generaluser_id, editable=False):
	gUser = get_object_or_404(User, id=generaluser_id)
	context = {
		'gUser': gUser,
		'editable': editable,
	}
	return render(request, 'RateMyServices/general_profile.html', context)

def professional_profile(request, professionaluser_id, service_id=None, editable=False):
	pUser = get_object_or_404(ProfessionalUser, id=professionaluser_id)
	nonEmptyReviewList = [] #a collection of nonempty review list for the professional user
	for i in pUser.service_set.all():
		tempList =[] #a list of nonempty review object for a single service
		for j in i.rating_set.exclude(description=''):
			tempList.append(j)
		nonEmptyReviewList.append(tempList)

	finalList = zip(pUser.service_set.all(),nonEmptyReviewList) 
	# e.g. [(serviceObj, nonEmptyreviewList for that service), ...]
	
	context = {
		'pUser': pUser,
		'editable': editable,
		'serviceWithReviews': finalList,
		'service_id': service_id,
	}
	return render(request, 'RateMyServices/professional_profile.html', context)

def upgrade_plans(request):
	gUser = User.objects.get(id=1) #id = 2 : for testing purposes
	pUser = get_object_or_404(ProfessionalUser, id=request.user.professionaluser_set.all()[0].id)
	if request.method == 'POST' and request.POST['premiumtype']=='Diamond':
		pUser.isDiamond = True
		pUser.isPlatinum = False
		pUser.save()
		return HttpResponseRedirect(reverse('RateMyServices:index'))
	elif request.method == 'POST' and request.POST['premiumtype']=='Platinum':
		pUser.isPlatinum = True
		pUser.isDiamond = False
		pUser.save()
		return HttpResponseRedirect(reverse('RateMyServices:index'))
	elif request.method == 'POST' and request.POST['premiumtype']=='noPremium':
		pUser.isPlatinum = False
		pUser.isDiamond = False
		pUser.save()
		return HttpResponseRedirect(reverse('RateMyServices:index'))
		
	context = {
		'gUser': gUser,
	}
	return render(request, 'RateMyServices/upgrade_plans.html', context)

def hire_service(request):
	pUser = get_object_or_404(ProfessionalUser, id=request.POST['provider'])
	gUser = get_object_or_404(User, id=request.user.id)
	service = get_object_or_404(Service, id=request.POST['service'])
	service.addOneHireCount()
	service.save()
	pUser.transaction_set.create(buyer=gUser, provider=pUser, service=service)
	return HttpResponseRedirect(reverse('RateMyServices:professional_profile', args=(pUser.id,)))

def addServicePage(request, generaluser_id):
	gUser = get_object_or_404(User, id=generaluser_id)
	return render(request,'RateMyServices/addServices.html', {'gUser': gUser})

def addService(request, generaluser_id):

RateMyServices/templates/RateMyServices/addServices.html
{% extends "RateMyServices/base.html" %}

{% block title %}Add a Service to Offer{% endblock %}

{% block content %}
<div class="container">
    <h1> Add a Service to Offer </h1>
    <br>
    <form action="{% url 'RateMyServices:addService' request.user.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="service">Service</label>
            <input type="text" class="form-control" name="service" placeholder="Enter the Service">    
        </div>
        <div class="form-group">
            <label for="rate">Rate</label>
            <input type="number" class="form-control" name="rate" placeholder="0.00">
        </div>
        <div class="form-group">
            <label for="isHour">Is This an Hourly Rate?</label>
            <select class="custom-select" name="isHour">
                <option selected>Choose...</option>
                <option value="Yes">Yes</option>
                <option value="No">No</option>
            </select>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" name="description" placeholder="Enter the Description of the service">
        </div>
        <button type="submit" class="btn btn-primary" name='submit' value='service'>Add Another Service</button>
        <button type="submit" class="btn btn-primary" name='submit' value='done'>Done</button>
    </form>
</div>
{% endblock %}

RateMyServices/templates/RateMyServices/base.html
<!DOCTYPE html>
<html>
	<head>
		{% load static %}
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>{% block title %}{% endblock %}</title>
		
		<link rel="shortcut icon" type="image/png" href="{% static 'RateMyServices/images/favicon.ico' %}"/>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'RateMyServices/css/customstyle_revemp.css' %}">
		<script src="https://use.fontawesome.com/c2ffd95238.js"></script>  
	</head>
	<body>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<header class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
			<div class="px-2 mr-auto"> <!-- user login block -->
				<a class="text-decoration-none" href="{%url 'RateMyServices:index'%}">
					<img class="logo d-inline" style="height: 48px; width: auto;" src='{% static "RateMyServices/images/logo_v2.svg"%}'>
					<!-- <h4 class="d-inline">RateMyServices</h4> -->
				</a>
			</div>
			
			<div class="d-none d-md-block"> <!-- search bar -->
				<form class="input-group" action="{% url 'RateMyServices:search' gUser.id %}" method="post">
					{% csrf_token %}
					<input class="rounded-left form-control w-25" type="text" placeholder="Search services or ..." name="search">
					<input class="form-control" type="text" placeholder="City" name="city">
					<input class="form-control" type="text" placeholder="State" name="state">
					<div class="input-group-append">
						<button class="btn btn-success" type="submit">GO!</button>
					</div>
				</form>
			</div>

			<div class="d-flex ml-auto pl-2 logo-section"> <!-- logo section -->
				{% include "RateMyServices/users_login_block.html" %}
			</div>
			<div class="d-flex"> <!-- search bar for small screen -->
				<div class="d-md-none col-12 header-search">
					<form class="input-group" action="{% url 'RateMyServices:search' gUser.id %}" method="post">
						{% csrf_token %}
						<input class="rounded-left form-control w-25" type="text" placeholder="Search services or ..." name="search">
						<input class="middle form-control" type="text" placeholder="City" name="city">
						<input class="middle form-control" type="text" placeholder="State" name="state">
						<div class="input-group-append">
							<button class="right btn btn-success" type="submit">GO!</button>
						</div>
					</form>
				</div>
			</div>
		</header>
		
		<div class="content">
			{% block content%}
			{% endblock%}
		</div>
	</body>
</html>

RateMyServices/templates/RateMyServices/becomeProUser.html
{% extends "RateMyServices/base.html" %}

{% block title %}Become a Professional User{% endblock %}

{% block content %}

<h1>Become A Professional</h1>
<div class="container">
    <form action="{% url 'RateMyServices:addProUser' request.user.id %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" name="title" placeholder="Enter your Title">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" class="form-control" name="description" placeholder="Description">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

{% endblock %}

RateMyServices/templates/RateMyServices/index.html
{% extends "RateMyServices/base.html" %}

{% block title %}Welcome to RateMyServices!!{% endblock %}

{% block content %}
<!-- Premium ProUser Ads -->
<div class="container-fluid px-0" style="height: 500px;background-color: lightgray;">
	<div id="PremiumpuserAds" class="carousel slide" data-ride="carousel" style="height: 100%;">
		<ol class="carousel-indicators btm-3">
			{% for i in diamondList %}
			<li data-target="#PremiumpuserAds" data-slide-to="{{forloop.counter0}}" {% if not forloop.counter0 %} class="active" {% endif %}></li>
			{% endfor %}
		</ol>
		<div class="carousel-inner">
			{% for i in diamondList %}
			<div class="carousel-item {% if not forloop.counter0 %} active {% endif %}" 
			{% if i.image %}
			style="background: url({{i.image.url}}) no-repeat; height: 500px; background-size: cover; background-position: center;"
			{% endif %}>
				<!-- <img src="i.Urls" class="d-block w-100" alt="..."> -->
				<div class="d-flex justify-content-center">
					<a href="{% url 'RateMyServices:professional_profile_service' i.provider.id i.id %}"><h1 class="mt-4 text-secondary rounded px-2" style="background-color: rgba(255, 255, 255, 0.6)">{{i.service}}</h1></a>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</div>	

<!-- paid ProUser Ads -->
<div class="container-fluid mt-3">
	<h4 class="text-muted">Promoted Ads</h4>
	<div class="row flex-row flex-nowrap overflow-auto">
		{% for i in platinumList %}
		<div class="col">
			{% include 'RateMyServices/reusableComponents/platinum_matchcards.html' %}
		</div>
		{% endfor %}
	</div>
</div>
<div class="container-fluid mt-3">
		<h4 class="text-muted">Some popular services:</h4>
		<div class="row flex-row flex-nowrap overflow-auto">
			{% if serviceList %}
			{% for i in serviceList %}
			<div class="col">
				{% include 'RateMyServices/reusableComponents/normal_matchcards.html' %}
			</div>
			{% endfor %}
			{% endif %}
		</div>
	</div>
{% endblock %}

RateMyServices/templates/RateMyServices/users_login_block.html
{% load static %}
{% if request.user.first_name == None %}
    <!-- <div class="form-row"> -->
        <div class="btn-group d-flex d-inline">
            <form class="mr-1" action="{% url 'RateMyServices:login' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-success btn-sm" type="submit">Log in</button>
            </form>
            <form class="" action="{% url 'RateMyServices:signup_view' %}" method="post">
                {% csrf_token %}
                <button class="btn btn-outline-success btn-sm" type="submit">Sign up</button>
            </form>
        </div>
    <!-- </div> -->
{% else %}
    <div class="btn-group">
        <button type="button" class="btn btn-outline-secondary p-1 dropdown-toggle d-flex align-items-center" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if request.user.profile_image %}
            <div class="rounded-circle mr-2" style="background: url({{request.user.profile_image.url}}) no-repeat; height: 50px; width: 50px; background-size: cover; background-position: center;"></div>
			{% else %}
			<div>
				<i class="fa fa-user-circle fa-3x mr-2"></i>
			</div> 
			{% endif %}
            <div class="d-flex flex-column mr-2">
                <div class="mb-1 p-0 text-nowrap overflow-hidden">{{request.user.get_full_name}}</div>
                {% if request.user.is_professional %}
                <div class="badge badge-pill badge-warning mr-auto" style="font-size: 9px;">professional user
                        {% if request.user.professionaluser_set.all.0.isDiamond or request.user.professionaluser_set.all.0.isPlatinum %}
                        <i class="fa fa-diamond" style="font-size: 1em;"></i>
                        {% endif %}
                </div>
                {% else %}
                    <div class="badge badge-pill badge-success mr-auto" style="font-size: 9px;">general user</div>
                {% endif %}
            </div>
        </button>

        <div class="dropdown-menu dropdown-menu-right px-0 py-1">
            <a class="dropdown-item" href="{% url 'RateMyServices:my_profile' %}">
                <span style="color: gray;" class="mr-2"><i class="fa fa-address-card fa-1x"></i></span>View My Profile </a>
            {% if request.user.is_professional %}
                <a class="dropdown-item" href="{% url 'RateMyServices:addServicePage' request.user.id %}">
                    <span style="color: gray;" class="mr-2"><i class="fa fa-plus fa-1x"></i></span>Add Services</a>
                {% if not request.user.professionaluser_set.all.0.isDiamond %}
                {% if not request.user.professionaluser_set.all.0.isPlatinum %}
                <a class="dropdown-item" href="{% url 'RateMyServices:becomePremium' %}">
                    <span style="color: gray;" class=""><i class="fa fa-diamond"></i></span> Upgrade to Premium
                </a>
                {% endif %}
                {% endif %}
                {% if request.user.professionaluser_set.all.0.isDiamond or request.user.professionaluser_set.all.0.isPlatinum %}
                <a class="dropdown-item" href="{% url 'RateMyServices:becomePremium' %}">
                    Manage my plans
                </a>
                {% endif %}
            {% else %}
                <a class="dropdown-item" href="{% url 'RateMyServices:becomeProUser' request.user.id %}">
                    <span style="color: gray;" class="mr-2"><i class="fa fa-briefcase fa-1x"></i></span>Become a Professional User</a>
            {% endif %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'RateMyServices:logout' %}">
                <span style="color: gray;" class="mr-2"><i class="fa fa-sign-out fa-1x"></i></span>Log out</a>
        </div>
    </div>
    <!-- <form action="{% url 'RateMyServices:logout' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-accent" type="submit">Log out!</button>
    </form>
    <a class='button btn-primary' >account settings</a> -->
{% endif %}